development:
    adapter: postgresql
    database: webmapps
    username: dcohen
    password: 
        
test:
    adapter: postgresql
    database: webmapps_test
    username: dcohen
    password:

production:
    adapter: postgresql
    database: webmapps_production
    username: dcohen
    password:
